name: leafletjs
version: 0.0.1
description: Dart wrapper for leafletjs map
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  func: any
  js: any
  observe: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
