name: leafletjs
version: 0.0.2
description: Dart wrapper for leafletjs map
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  observe: any
  polymer: 1.0.0-rc.6
  reflectable: any
  source_gen: '>=0.4.0'
  web_components: any
  dart_to_js_script_rewriter: any
dev_dependencies:
  js_wrapping:
    git: https://github.com/vgordievskiy/dart-js-wrapping.git
    version: '>=0.2.0'
transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.bootstrap.initialize.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
- dart_to_js_script_rewriter
