name: leafletjs
version: 0.0.1
description: Dart wrapper for leafletjs map
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  func: any
  js: any
  observe: any
  angular2: '2.0.0-beta.1'
transformers:
- observe
- angular2:
    entry_points: [web/index.dart]
- $dart2js:
    minify: true
    checked: true
    sourceMaps: false
